server:
  port: 8010
spring:
  application:
    name: order-service
#使用Consul作为注册中心
#  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        hostname: 127.0.0.1
#使用Zookeeper作为注册中心
#  cloud:
#    zookeeper:
#      connect-string: 127.0.0.1:2181
#使用Eureka作为注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:9100/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    #EurekaClient向EurekaServer发送心跳的间隔时间（默认为30s，开发环境建议设置较小值）
    lease-renewal-interval-in-seconds: 1
    #EurekaServer在收到最后一次心跳后的等待时间，超过则剔除EurekaClient（默认为90s，开发环境建议设置较小值）
    lease-expiration-duration-in-seconds: 2
    hostname: 127.0.0.1